[package]
name = "guessing_game"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.5" 
  # "^0.8.5" 의 축약이며 이 규칙은 전세계 개발자들의 공통 규칙인 SemVer를 따른다. 
  # ^ <<< 호환되는 마지노선인 0.8.x 까지만 최신버전을 알아보고 설치 or 업뎃하겠다는 뜻이다. 0.9.0 이상은 마이너(기능)의 변경이기에 호환성을 보장하지 못한다. 